name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # This line specifies the distribution
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file automation/pom.xml

    - name: Run unit tests
      run: mvn test --file automation/pom.xml
